version: "3.7"

services:
  backend:
    build: .
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo:27017
    ports:
      - target: 4000
        published: 4001

  frontend:
    build: ../frontend
    restart: always
    depends_on:
      - backend
    ports:
      - target: 80
        published: 3001

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - target: 27017
        published: 27018
        protocol: tcp
        mode: host

